baseURL = "/"
languageCode = "en-us"
title = "izdwuut's personal place"
theme = "hugo-paper"
pygmentsCodefences = true

[params]
    githubProfile = "https://github.com/izdwuut"
    sources = "https://github.com/izdwuut/izdwuut.github.io/tree/dev"
    dateForm = "2006-01-02"
    author = "izdwuut"
    homeTypes = "posts, tutorials"

[menu]
    [[menu.main]]
        name = "Home"
        url = "/"
        weight = -100
    [[menu.main]]
        name = "Tutorials"
        url = "/tutorials/"
        weight = -90